# Generated by Django 3.2.9 on 2022-01-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220101_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='readers',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
