# Generated by Django 4.0 on 2022-01-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_dislike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
