# Generated by Django 4.0 on 2022-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesAuthors',
            field=models.TextField(blank=True, default=0, null=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likesCount',
            field=models.IntegerField(blank=True, default=0, null=0, verbose_name='Лайки'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
