# Generated by Django 4.0 on 2022-01-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_likesauthors_alter_post_likescount_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likesAuthors',
        ),
    ]
