# Generated by Django 4.0 on 2022-01-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_likesauthors'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likesAuthors',
            field=models.TextField(blank=True, null=0),
        ),
    ]
