# Generated by Django 3.2.9 on 2022-01-08 11:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=25, verbose_name='password1')),
                ('password2', models.CharField(default='SOME STRING', max_length=25, verbose_name='password2')),
                ('firstname', models.CharField(max_length=30, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('patronymic', models.CharField(max_length=30, verbose_name='patronymic')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('country', models.CharField(default='Global', max_length=30, verbose_name='country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
