# Generated by Django 3.2.9 on 2021-12-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=25, verbose_name='password')),
                ('firstname', models.CharField(max_length=30, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('patronymic', models.CharField(max_length=30, verbose_name='patronymic')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('registration', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('country', models.CharField(default='Global', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
