# Generated by Django 3.2.9 on 2022-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_login_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='SOME STRING', max_length=25, verbose_name='password2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='Global', max_length=30, verbose_name='county'),
        ),
    ]
